### ISSUE TITLE
Project stuck on "website-web-1  | Waiting for PostgreSQL to become available..." on M1 Mac

### ISSUE THREAD

**Issue by pietrogallace** [michael-yin/wagtail-bootstrap-blog#139]
### What happened?

I've followed the steps described on the e-book "Build Blog With Wagtail CMS (4.0.0)" on my M1 Mac and when Dockerizing the project (Chapter 4) I start encountering this issue.

The docker image and container build just fine but when I run the docker-compose logs -f command I encounter this issue

<img width="1314" alt="Screenshot 2023-02-02 at 10 43 58 AM" src="https://user-images.githubusercontent.com/109516111/216289173-6de05525-dbf8-49c5-8bbc-40b08b0c402d.png">

### Additional details 

I've followed the steps correctly, and the Dockerfile, the entrypoint, the start and the docker-compose.yml all match the book.

With the exact same configuration on my Windows 10 PC I don't encounter any problems at all.

**Comment by michael-yin** [comment]
@PGallace98 

Thanks for your report

When you develop on M1 Mac, could you update the `posgres image` to https://hub.docker.com/r/arm64v8/postgres/ which is Arm Docker images instead of default x86/amd64

Since I have no M1/M2 Mac in hand so I can not not test if it works, but I hope it can help.

Thx.

**Comment by pietrogallace** [comment]
@michael-yin 

Thank you for the reply.

Unfortunately updating to postgres arm image didn't fix the problem.

docker-compose.yml file for reference 

<img width="986" alt="Screenshot 2023-02-03 at 3 00 00 PM" src="https://user-images.githubusercontent.com/109516111/216622094-5d319bb5-6cdc-43b3-97e1-c2e60fecbff1.png">

**Comment by michael-yin** [comment]
@PGallace98 

I did some research on this issue and figured it out

### Why this issue happen

On apple silicon, we got [Postgresql SCRAM authentication problem?](https://stackoverflow.com/questions/62807717/how-can-i-solve-postgresql-scram-authentication-problem) so the program hang with "Waiting for PostgreSQL to become available" message.

### Solution

We can use Rosetta to make our program work with "linux/amd64" instead of the "arm64"

Below are the steps:

1. Please remove all "docker containers" and "docker images" for a clean env. https://stackoverflow.com/questions/44785585/how-can-i-delete-all-local-docker-images
2. Git clone the project again without modification.

And then run command below

```
# install rosetta
softwareupdate --install-rosetta

# tell docker to build and run on amd64 platform
export DOCKER_DEFAULT_PLATFORM=linux/amd64
docker-compose build
docker-compose up
```

I already tested it on real M1 Mac and it worked.

Thx

**Comment by pietrogallace** [comment]
Thanks a lot it worked.
